environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"

clone_depth: 5

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off
